import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Scanner;
public class Practice {

    public static void main(String[] args) {
        Scanner x = new Scanner(System.in);
        boolean loop = true;
        do {
            try {
                System.out.println("Enter two integers>> ");
                int xx = x.nextInt();
                int yy = x.nextInt();
                int z = quotient(xx, yy);
                System.out.println("The quotient is: " + z);
                loop = false;
            } catch (Exception e) {
               //e.printStackTrace(); //Displays where the exception originated
               // System.out.println(e.getMessage()); //Divisor cannot be zero.
                // System.out.println(e.toString()); //java.lang.ArithmeticException: Divisor cannot be zero
            }
        } while (loop == true);

    }
    private static int quotient(int number1, int number2) throws ArithmeticException  {
        if (number2 == 0)
            //method throws exception to the calling method
            throw new ArithmeticException("Divisor cannot be zero.");
        return number1 / number2;
    }
}
